### ISSUE TITLE
AWS shut down?

### ISSUE THREAD

**Issue by jongwuner** [22hours/official-website#2]
## 문제상황
- host:3000 접속(성공)이 되는 찰나에 AWS EC2 펑 터져버림.

## 원인
- 프리티어에서 벗어나면 해결이 되는문제?
- 아니면 어떤 과정 상에서 실수가 있었는지?

**Comment by jongwuner** [comment]
Solved 191030

**Comment by jongwuner** [comment]
우선 ssh에 다수가 동시에 접속하면 cpu 100을 뚫으면서 마비가 되는 느낌이 있다.
정확한 원인은 모르겠지만, ssh 접속을 종료하고나서는 cpu가 정상으로 돌아오고, 3000포트도 원활하게 접속된다.

**Comment by winterlood** [comment]
FreeTier로는 서버를 운영하는데, 제한 사항이 분명히 있음

다수가 ssh에 접속하지 못한다면 우선 ubuntu os를 사용하는 의미가 없고,

시험 호스팅 기간을 거쳐 충분히 경쟁사들과 논의 후 결정하도록 합시다.
